export default [
    {
      date: "jan, 13 2020",
      type: "move in/Out cleaning",
      customer: "Stephanie rude",
      frequency: "Bi-weekly",
      address: "Nairobi",
      price: "$400",
    },
    {
      date: "jan, 13 2020",
      type: "move in/Out cleaning",
      customer: "Stephddddanie rude",
      frequency: "dweekly",
      address: "Nairobi",
      price: "$400",
    },
    {
      date: "jan, 13 2020",
      type: "move in/Out cleaning",
      customer: "Stephanie rude",
      frequency: "Bi-weekly",
      address: "Nairobi",
      price: "$400",
    },    {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephanie rude",
        frequency: "Bi-weekly",
        address: "Nairobi",
        price: "$400",
      },
      {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephddddanie rude",
        frequency: "dweekly",
        address: "Nairobi",
        price: "$400",
      },
      {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephanie rude",
        frequency: "Bi-weekly",
        address: "Nairobi",
        price: "$400",
      },    {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephanie rude",
        frequency: "Bi-weekly",
        address: "Nairobi",
        price: "$400",
      },
      {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephddddanie rude",
        frequency: "dweekly",
        address: "Nairobi",
        price: "$400",
      },
      {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephanie rude",
        frequency: "Bi-weekly",
        address: "Nairobi",
        price: "$400",
      },    {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephanie rude",
        frequency: "Bi-weekly",
        address: "Nairobi",
        price: "$400",
      },
      {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephddddanie rude",
        frequency: "dweekly",
        address: "Nairobi",
        price: "$400",
      },
      {
        date: "jan, 13 2020",
        type: "move in/Out cleaning",
        customer: "Stephanie rude",
        frequency: "Bi-weekly",
        address: "Nairobi",
        price: "$400",
      },    {
      date: "jan, 13 2020",
      type: "move in/Out cleaning",
      customer: "Stephanie rude",
      frequency: "Bi-weekly",
      address: "Nairobi",
      price: "$400",
    },
    {
      date: "jan, 13 2020",
      type: "move in/Out cleaning",
      customer: "Stephddddanie rude",
      frequency: "dweekly",
      address: "Nairobi",
      price: "$400",
    },
    {
      date: "jan, 13 2020",
      type: "move in/Out cleaning",
      customer: "Stephanie rude",
      frequency: "Bi-weekly",
      address: "Nairobi",
      price: "$400",
    },
  
  ]